version: "3.8"
services:
    backend:
        container_name: "webapi"
        depends_on:
            - "rabbitmq3"
            - "hub"
        build:
            context: .
            dockerfile: Dockerfile.WebApi
        image: "webapi"
        ports:
            - "5000:5000"
        networks:
            test:
            
    hub:
        container_name: "hub"
        depends_on:
            - "rabbitmq3"
        build:
            context: .
            dockerfile: Dockerfile.Hub
        image: "hub"
        ports:
            - "6000:6000"
        networks:
            test:

    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
        networks:
            test:
            
    redis:
        image: "redis:alpine"
        container_name: "redis"
        command: redis-server
        ports:
            - "6379:6379"
            
networks:
    test:
        driver: bridge